import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainLogin extends JFrame implements ActionListener {
    private JPanel jp1;
    private JPanel jp2;
    private JPanel jp3;
    private JPanel jp4;
    private JButton button1;
    private JButton button2;
    static JFrame frame;

    public MainLogin() {
        frame = new JFrame("Main Login: 请先登录!");
        frame.setLayout(new GridLayout(3, 1));
        jp1 = new JPanel();
        JLabel jlabel = new JLabel("请选择你的登录身份");
        jp1.add(jlabel);
        jp2 = new JPanel();
        jp3 = new JPanel();
        button1 = new JButton("管理员");
        button2 = new JButton("学生");
        jp2 = new JPanel();
        jp2.add(button1);
        jp2.add(button2);
        frame.add(jp3);
        frame.add(jp1);
        frame.add(jp2);
        frame.setSize(500, 350);
        frame.setLocationRelativeTo(null);//Display in the middle of the screen (center display)
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//Exit and close JFrame
        frame.setVisible(true);
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setVisible(false);
                new Administratorlogin();
            }
        });
        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setVisible(false);
                new StudentLogin();
            }
        });


    }


    public static void main(String[] args) {
        MainLogin mainLogin = new MainLogin();

    }

    @Override
    public void actionPerformed(ActionEvent e) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    }
}
